samples = 1000
warmup = 100

do_run = "./a.out"
do_build = "gcc *.c $PAC_OBJ $PAC_FLAGS"

[benchmarks.ammunition]
path = "tacle-bench/bench/sequential/ammunition"

[benchmarks.bitcount]
path = "tacle-bench/bench/kernel/bitcount"

[benchmarks.fmref]
path = "tacle-bench/bench/sequential/fmref"

[benchmarks.huff_dec]
path = "tacle-bench/bench/sequential/huff_dec"

[benchmarks.isqrt]
path = "tacle-bench/bench/kernel/isqrt"

[benchmarks.mpeg2]
path = "tacle-bench/bench/sequential/mpeg2"

[benchmarks.rijndael_dec]
path = "tacle-bench/bench/sequential/rijndael_dec"

[benchmarks.cjpeg_wrbmp]
path = "tacle-bench/bench/sequential/cjpeg_wrbmp"

[benchmarks.gsm_dec]
path = "tacle-bench/bench/sequential/gsm_dec"

[benchmarks.huff_enc]
path = "tacle-bench/bench/sequential/huff_enc"

[benchmarks.lms]
path = "tacle-bench/bench/kernel/lms"

[benchmarks.md5]
path = "tacle-bench/bench/kernel/md5"

[benchmarks.ndes]
path = "tacle-bench/bench/sequential/ndes"

[benchmarks.rijndael_enc]
path = "tacle-bench/bench/sequential/rijndael_enc"

[benchmarks.sha]
path = "tacle-bench/bench/kernel/sha"

[benchmarks.audiobeam]
path = "tacle-bench/bench/sequential/audiobeam"

[benchmarks.filterbank]
path = "tacle-bench/bench/kernel/filterbank"

[benchmarks.gsm_enc]
path = "tacle-bench/bench/sequential/gsm_enc"

[benchmarks.insertsort]
path = "tacle-bench/bench/kernel/insertsort"

[benchmarks.ludcmp]
path = "tacle-bench/bench/kernel/ludcmp"

[benchmarks.minver]
path = "tacle-bench/bench/kernel/minver"

[benchmarks.powerwindow]
path = "tacle-bench/bench/app/powerwindow"

[benchmarks.susan]
path = "tacle-bench/bench/sequential/susan"
